export default {
  STATIC_PATH: 'STATIC_PATH',
  JWT_ACCESS_SECRET: 'JWT_ACCESS_SECRET',
  JWT_REFRESH_SECRET: 'JWT_REFRESH_SECRET',
  JWT_ACCESS_EXP: 'JWT_ACCESS_EXP',
  JWT_REFRESH_EXP: 'JWT_REFRESH_EXP',
  NODE_ENV: 'NODE_ENV',
};
